export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Request Engine Agent API",
    version: "1.0.0",
    description: "API determinista para catálogo, disponibilidad, reservas y colas. Un agente nunca debe crear una reserva sin un offerId vigente.",
  },
  servers: [{ url: "/v1" }],
  security: [{ bearerAuth: [] }],
  paths: {
    "/onboarding/organizations": { post: { operationId: "onboarding.createOrganization", summary: "Crea organización y sede inicial en borrador", security: [], responses: { "201": { description: "Borrador creado" } } } },
    "/onboarding/otp/request": { post: { operationId: "onboarding.requestOtp", summary: "Envía OTP al correo permitido", security: [], responses: { "200": { description: "OTP aceptado por el adaptador" } } } },
    "/onboarding/otp/verify": { post: { operationId: "onboarding.verifyOtp", summary: "Verifica el propietario", security: [], responses: { "200": { description: "Resultado de verificación" } } } },
    "/onboarding/provision-pilot": { post: { operationId: "onboarding.provisionPilot", summary: "Aprovisiona Chatwoot, usuario técnico, Agent Bot y Evolution", responses: { "200": { description: "Estado reanudable y QR opcional" } } } },
    "/organizations/publish": { post: { operationId: "organization.publish", summary: "Publica tras validaciones y consentimiento explícito", responses: { "200": { description: "Organización publicada" } } } },
    "/locations": { post: { operationId: "locations.create", summary: "Crea una sede", responses: { "201": { description: "Sede creada" } } } },
    "/services": { post: { operationId: "services.create", summary: "Crea un servicio agendable", responses: { "201": { description: "Servicio creado" } } } },
    "/resources": { post: { operationId: "resources.create", summary: "Crea personal, sala o equipo", responses: { "201": { description: "Recurso creado" } } } },
    "/calendars": { post: { operationId: "calendars.create", summary: "Crea un calendario IANA", responses: { "201": { description: "Calendario creado" } } } },
    "/calendars/rules": { post: { operationId: "calendars.setWeeklyRules", summary: "Reemplaza reglas semanales", responses: { "200": { description: "Reglas validadas" } } } },
    "/calendars/exceptions": { post: { operationId: "calendars.addException", summary: "Crea cierre, apertura u horario especial", responses: { "200": { description: "Excepción creada" } } } },
    "/people": { post: { operationId: "people.create", summary: "Crea una persona", responses: { "201": { description: "Persona creada" } } } },
    "/people/identifiers": { post: { operationId: "people.addIdentifier", summary: "Cifra e indexa ciegamente un documento", responses: { "201": { description: "Identificador enmascarado" } } } },
    "/insurance/coverages": { post: { operationId: "insurance.createCoverage", summary: "Relaciona paciente, afiliación y pagador", responses: { "201": { description: "Cobertura no verificada" } } } },
    "/providers/credentials": { post: { operationId: "providers.createCredential", summary: "Registra exequátur o licencia cifrada", responses: { "201": { description: "Credencial no verificada" } } } },
    "/catalog/search": { post: { operationId: "catalog.search", summary: "Busca un máximo de cinco servicios", responses: { "200": { description: "Servicios verificados" } } } },
    "/availability/summarize": { post: { operationId: "availability.summarize", summary: "Resume disponibilidad por fecha y turno", responses: { "200": { description: "Resumen agregado" } } } },
    "/availability/options": { post: { operationId: "availability.listOptions", summary: "Emite hasta cinco ofertas temporales", responses: { "200": { description: "Ofertas opacas y verificadas" }, "409": { description: "Sin disponibilidad" } } } },
    "/bookings": { post: { operationId: "booking.create", summary: "Crea una reserva desde una oferta", parameters: [{ in: "header", name: "Idempotency-Key", required: true, schema: { type: "string" } }], responses: { "201": { description: "Reserva pendiente de confirmación" }, "409": { description: "Oferta vencida o capacidad agotada" } } } },
    "/bookings/transition": { post: { operationId: "booking.transition", summary: "Confirma, cancela o completa una reserva", responses: { "200": { description: "Estado actualizado" } } } },
    "/bookings/reschedule": { post: { operationId: "booking.reschedule", summary: "Reprograma atómicamente usando una nueva oferta", parameters: [{ in: "header", name: "Idempotency-Key", required: true, schema: { type: "string" } }], responses: { "200": { description: "Nueva reserva y cadena histórica" } } } },
    "/queue/check-in": { post: { operationId: "queue.checkIn", summary: "Hace check-in y emite el turno autoritativo", responses: { "201": { description: "Ticket y estimación no garantizada" } } } },
    "/waitlist": { post: { operationId: "waitlist.join", summary: "Entra a una lista de espera", responses: { "201": { description: "Entrada creada" } } } },
    "/waitlist/accept": { post: { operationId: "waitlist.accept", summary: "Acepta atómicamente una oferta; una sola persona gana", responses: { "200": { description: "Reserva creada o espacio perdido" } } } },
    "/agent/runtime-bundle": { get: { operationId: "agent.runtimeBundle", summary: "Devuelve prompts publicados, tools y contexto mínimo", responses: { "200": { description: "Bundle versionado" } } } },
    "/integrations/notification-callback": { post: { operationId: "integration.notificationCallback", summary: "Callback HMAC idempotente con intención tipada", security: [{ webhookSignature: [] }], responses: { "200": { description: "Callback procesado" } } } },
  },
  components: {
    securitySchemes: {
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "API key" },
      webhookSignature: { type: "apiKey", in: "header", name: "X-Request-Engine-Signature" },
    },
  },
} as const
