# Frozen reviewed executable surface per runtime group role, in the
# ``schema.function(oidvectortypes)`` form. Every entry is introduced by an
# accepted, reviewed migration grant; this catalog must change only together
# with a new reviewed grant and its own evidence.

EXPECTED_FUNCTIONS = {
    "request_engine_app": {
        "request_cmd.acquire_idempotency(uuid, uuid, text, text, text)",
        "request_cmd.cancel_scheduled_action(uuid, uuid)",
        "request_cmd.complete_idempotency(uuid, jsonb)",
        "request_cmd.lock_outbox_message_claim(uuid, uuid, uuid)",
        "request_cmd.lock_recovery_source_revision(uuid, uuid)",
        "request_cmd.lock_scheduled_action_claim(uuid, uuid)",
        "request_cmd.lock_shared_capacity_roots(uuid, uuid[])",
        "request_cmd.schedule_recovery_reassessment(uuid, uuid, bigint)",
        "request_engine.current_authenticated_principal_id()",
        "request_engine.current_correlation_id()",
        "request_engine.current_organization_id()",
        "request_engine.lock_current_party_authority(uuid, uuid, uuid, text)",
        "request_engine.lookup_active_service_classification(text)",
        "request_engine.lookup_service_classification(uuid)",
        "request_engine.read_discovery_booking_handoff(text)",
        "request_engine.resolve_current_party_authority(uuid, uuid, uuid, text)",
    },
    "request_engine_worker": {
        "request_cmd.claim_outbox_messages(integer, interval)",
        "request_cmd.claim_provider_events(integer, interval)",
        "request_cmd.claim_scheduled_actions(integer, interval)",
        "request_cmd.complete_outbox_message(uuid, uuid)",
        "request_cmd.complete_provider_event(uuid, uuid)",
        "request_cmd.complete_scheduled_action(uuid, uuid)",
        "request_cmd.dead_letter_outbox_message(uuid, uuid, text)",
        "request_cmd.dead_letter_provider_event(uuid, uuid, text)",
        "request_cmd.dead_letter_scheduled_action(uuid, uuid, text)",
        "request_cmd.find_recovery_sweep_scopes(integer)",
        "request_cmd.lock_scheduled_action_claim(uuid, uuid)",
        "request_cmd.reject_provider_event(uuid, uuid, text)",
        "request_cmd.renew_outbox_message_lease(uuid, uuid, interval)",
        "request_cmd.renew_provider_event_lease(uuid, uuid, interval)",
        "request_cmd.renew_scheduled_action_lease(uuid, uuid, interval)",
        "request_cmd.retry_outbox_message(uuid, uuid, timestamp with time zone, text)",
        "request_cmd.retry_outbox_message_after(uuid, uuid, interval, text)",
        "request_cmd.retry_provider_event_after(uuid, uuid, interval, text)",
        "request_cmd.retry_scheduled_action(uuid, uuid, timestamp with time zone, text)",
        "request_cmd.retry_scheduled_action_after(uuid, uuid, interval, text)",
        "request_engine.current_authenticated_principal_id()",
        "request_engine.current_correlation_id()",
        "request_engine.current_organization_id()",
    },
    "request_engine_admin": {
        "request_admin.activate_shared_capacity_binding(uuid, uuid, uuid, text, text)",
        "request_admin.create_global_identity(text, text, text, text)",
        "request_admin.create_service_classification(text, text, text, text)",
        "request_admin.create_shared_capacity_identity(uuid, text, text)",
        "request_admin.replay_dead_outbox_message(uuid, uuid, integer, text)",
        "request_admin.replay_dead_scheduled_action(uuid, uuid, integer, text)",
        "request_admin.replay_provider_event(uuid, uuid, integer, text)",
        "request_admin.retire_service_classification(uuid, bigint, text, text)",
        "request_admin.revoke_shared_capacity_binding(uuid, text, text)",
        "request_cmd.cancel_scheduled_action(uuid, uuid)",
        "request_cmd.claim_outbox_messages(integer, interval)",
        "request_cmd.claim_provider_events(integer, interval)",
        "request_cmd.claim_scheduled_actions(integer, interval)",
        "request_cmd.complete_outbox_message(uuid, uuid)",
        "request_cmd.complete_provider_event(uuid, uuid)",
        "request_cmd.complete_scheduled_action(uuid, uuid)",
        "request_cmd.dead_letter_outbox_message(uuid, uuid, text)",
        "request_cmd.dead_letter_provider_event(uuid, uuid, text)",
        "request_cmd.dead_letter_scheduled_action(uuid, uuid, text)",
        "request_cmd.find_recovery_sweep_scopes(integer)",
        "request_cmd.lock_outbox_message_claim(uuid, uuid, uuid)",
        "request_cmd.lock_recovery_source_revision(uuid, uuid)",
        "request_cmd.lock_shared_capacity_roots(uuid, uuid[])",
        "request_cmd.reject_provider_event(uuid, uuid, text)",
        "request_cmd.renew_outbox_message_lease(uuid, uuid, interval)",
        "request_cmd.renew_provider_event_lease(uuid, uuid, interval)",
        "request_cmd.renew_scheduled_action_lease(uuid, uuid, interval)",
        "request_cmd.retry_outbox_message(uuid, uuid, timestamp with time zone, text)",
        "request_cmd.retry_outbox_message_after(uuid, uuid, interval, text)",
        "request_cmd.retry_provider_event_after(uuid, uuid, interval, text)",
        "request_cmd.retry_scheduled_action(uuid, uuid, timestamp with time zone, text)",
        "request_cmd.retry_scheduled_action_after(uuid, uuid, interval, text)",
        "request_engine.current_authenticated_principal_id()",
        "request_engine.current_correlation_id()",
        "request_engine.current_organization_id()",
        "request_engine.guard_discovery_handoff_latest_version()",
        "request_engine.guard_discovery_handoff_reservation()",
        "request_engine.has_active_discovery_mapping(uuid)",
        (
            "request_engine.issue_discovery_booking_handoff(text, uuid, bigint, uuid, "
            "bigint, uuid, uuid, jsonb, timestamp with time zone)"
        ),
        "request_engine.lock_current_party_authority(uuid, uuid, uuid, text)",
        "request_engine.read_discovery_booking_handoff(text)",
        "request_engine.resolve_current_party_authority(uuid, uuid, uuid, text)",
        (
            "request_engine.search_discovery_candidates_v2(text, double precision, "
            "double precision, integer, timestamp with time zone, "
            "timestamp with time zone, integer)"
        ),
    },
}
