-- Generated from the audited Request Engine role catalog.
-- Credentials are intentionally forbidden from this payload.

CREATE ROLE "request_bootstrap_definer" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION BYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_admin" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION BYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_app" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_discovery" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_discovery_definer" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION BYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_schema_owner" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_engine_worker" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_platform_control" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_platform_control_definer" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION BYPASSRLS CONNECTION LIMIT -1;
CREATE ROLE "request_platform_definer" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION BYPASSRLS CONNECTION LIMIT -1;
