from .http_surface import (
    PROBE_UUID,
    PROBE_UUID_2,
    HttpProbe,
    PublicHttpOperation,
    TenantIsolationMode,
)

STAFF_HTTP_OPERATIONS: tuple[PublicHttpOperation, ...] = (
    PublicHttpOperation(
        "staff.invitation.create",
        "POST",
        "/v1/staff/invitations",
        "staff.invite",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            "/v1/staff/invitations",
            body={
                "email": "invited@example.test",
                "provenance_reference": "surface-probe",
            },
        ),
    ),
    PublicHttpOperation(
        "staff.invitation.list",
        "GET",
        "/v1/staff/invitations",
        "staff.read",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe("/v1/staff/invitations"),
    ),
    PublicHttpOperation(
        "staff.invitation.get",
        "GET",
        "/v1/staff/invitations/{invitation_id}",
        "staff.read",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(f"/v1/staff/invitations/{PROBE_UUID}"),
    ),
    PublicHttpOperation(
        "staff.invitation.resend",
        "POST",
        "/v1/staff/invitations/{invitation_id}:resend",
        "staff.invite",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            f"/v1/staff/invitations/{PROBE_UUID}:resend",
            body={
                "expected_revision": 1,
                "provenance_reference": "surface-probe",
            },
        ),
    ),
    PublicHttpOperation(
        "staff.invitation.revoke",
        "POST",
        "/v1/staff/invitations/{invitation_id}:revoke",
        "staff.invite",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            f"/v1/staff/invitations/{PROBE_UUID}:revoke",
            body={
                "expected_revision": 1,
                "provenance_reference": "surface-probe",
            },
        ),
    ),
    PublicHttpOperation(
        "staff.overview",
        "GET",
        "/v1/staff/overview",
        "staff.read",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe("/v1/staff/overview"),
    ),
    PublicHttpOperation(
        "staff.list",
        "GET",
        "/v1/staff/members",
        "staff.read",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe("/v1/staff/members"),
    ),
    PublicHttpOperation(
        "staff.get",
        "GET",
        "/v1/staff/members/{membership_id}",
        "staff.read",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(f"/v1/staff/members/{PROBE_UUID}"),
    ),
    PublicHttpOperation(
        "staff.invite.native",
        "POST",
        "/v1/staff/members/native",
        "staff.invite",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            "/v1/staff/members/native",
            body={
                "identity_authority_id": PROBE_UUID,
                "native_identity_id": PROBE_UUID_2,
                "provenance_reference": "surface-probe",
            },
        ),
    ),
    PublicHttpOperation(
        "staff.authority.replace",
        "PUT",
        "/v1/staff/members/{membership_id}/authority",
        "staff.manage_authority",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            f"/v1/staff/members/{PROBE_UUID}/authority",
            body={
                "expected_authority_revision": 1,
                "desired_capabilities": ["staff.invite"],
                "provenance_reference": "surface-probe",
            },
        ),
    ),
    PublicHttpOperation(
        "staff.authority.plan",
        "POST",
        "/v1/staff/members/{membership_id}/authority:plan",
        "staff.plan_authority",
        False,
        False,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            f"/v1/staff/members/{PROBE_UUID}/authority:plan",
            body={
                "expected_authority_revision": 1,
                "desired_capabilities": ["staff.invite"],
            },
        ),
    ),
    PublicHttpOperation(
        "staff.membership.transition",
        "PUT",
        "/v1/staff/members/{membership_id}/status",
        "staff.manage_membership",
        True,
        True,
        TenantIsolationMode.CONTEXTUAL,
        HttpProbe(
            f"/v1/staff/members/{PROBE_UUID}/status",
            body={
                "expected_revision": 1,
                "target_status": "suspended",
                "provenance_reference": "surface-probe",
            },
        ),
    ),
)
