from request_engine.platform.security.capability_types import (
    CapabilityDefinition,
    CapabilityExposure,
    RevisionPolicy,
    command_capability,
    query_capability,
)

WAITLIST_REMINDER_CAPABILITIES: tuple[CapabilityDefinition, ...] = (
    command_capability(
        "waitlist.join",
        CapabilityExposure.PUBLIC,
        "Join an Offering waitlist for an authorized subject Party.",
        party_scope="waitlist.join",
        override_capability="waitlist.subject_override",
    ),
    query_capability(
        "waitlist.read",
        CapabilityExposure.PUBLIC,
        "Read a waitlist entry for an authorized subject Party.",
        party_scope="waitlist.manage",
        override_capability="waitlist.subject_override",
    ),
    command_capability(
        "waitlist.leave",
        CapabilityExposure.PUBLIC,
        "Cancel an active waitlist entry for an authorized subject Party.",
        revision=RevisionPolicy.REQUIRED,
        party_scope="waitlist.manage",
        override_capability="waitlist.subject_override",
    ),
    command_capability(
        "waitlist.accept_offer",
        CapabilityExposure.PUBLIC,
        "Accept an active SlotOffer and atomically promote its hold to a Reservation.",
        revision=RevisionPolicy.REQUIRED,
        party_scope="waitlist.manage",
        override_capability="waitlist.subject_override",
    ),
    command_capability(
        "waitlist.decline_offer",
        CapabilityExposure.PUBLIC,
        "Decline an active SlotOffer and release its capacity hold.",
        revision=RevisionPolicy.REQUIRED,
        party_scope="waitlist.manage",
        override_capability="waitlist.subject_override",
    ),
    command_capability(
        "waitlist.subject_override",
        CapabilityExposure.OPERATOR,
        "Permission to operate on waitlist subjects without delegated Party authority.",
        runtime_available=False,
    ),
    command_capability(
        "waitlist.create_opportunity",
        CapabilityExposure.INTERNAL,
        "Create a deduplicated slot opportunity from a capacity-release event.",
    ),
    command_capability(
        "reminders.create_plan",
        CapabilityExposure.PUBLIC,
        "Create a durable recurring ReminderPlan for an authorized subject Party.",
        party_scope="reminders.manage",
        override_capability="reminders.subject_override",
        legacy_aliases=frozenset({"communications.create_reminder_plan"}),
    ),
    query_capability(
        "reminders.read",
        CapabilityExposure.PUBLIC,
        "Read a ReminderPlan for an authorized subject Party.",
        party_scope="reminders.manage",
        override_capability="reminders.subject_override",
    ),
    command_capability(
        "reminders.cancel_plan",
        CapabilityExposure.PUBLIC,
        "Cancel an active ReminderPlan for an authorized subject Party.",
        revision=RevisionPolicy.REQUIRED,
        party_scope="reminders.manage",
        override_capability="reminders.subject_override",
        legacy_aliases=frozenset({"communications.cancel_reminder_plan"}),
    ),
    command_capability(
        "communications.configure",
        CapabilityExposure.OPERATOR,
        "Configure the organization channel policy for one communication purpose.",
    ),
    command_capability(
        "reminders.subject_override",
        CapabilityExposure.OPERATOR,
        "Permission to operate on ReminderPlans without delegated Party authority.",
        runtime_available=False,
    ),
)
